name: Deploy to Vercel

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: vercel-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel Environment Information
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          set -euo pipefail
          FLAGS=""
          if [ -n "${VERCEL_PROJECT_ID:-}" ] && [ -n "${VERCEL_ORG_ID:-}" ]; then
            FLAGS="--project $VERCEL_PROJECT_ID --org $VERCEL_ORG_ID"
          fi
          vercel pull --yes --environment=production $FLAGS --token "$VERCEL_TOKEN"

      - name: Build (Vercel build)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          set -euo pipefail
          vercel build --token "$VERCEL_TOKEN"

      - name: Deploy (Production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          set -euo pipefail
          FLAGS=""
          if [ -n "${VERCEL_PROJECT_ID:-}" ] && [ -n "${VERCEL_ORG_ID:-}" ]; then
            FLAGS="--project $VERCEL_PROJECT_ID --org $VERCEL_ORG_ID"
          fi
          vercel deploy --prebuilt --prod $FLAGS --token "$VERCEL_TOKEN"
